from pydantic import BaseModel
from typing import Optional
from datetime import datetime


class GuidanceItem(BaseModel):
    """
    Mirrors the ground truth structure exactly.
    This is what the LLM returns via structured output.
    guidance_value is a string to preserve ranges like "18-20".
    """
    passage: str
    speaker: str
    page_number: int
    metric: str  # from controlled vocabulary in prompt_v8 — e.g. "ebitda_margin_pct"
    guidance_value: Optional[str] = None  # string, not float — preserves "18-20" ranges
    guidance_unit: Optional[str] = None   # "%" or "crore" or null
    timeline: str                          # e.g. "FY27" or "H1 FY27"
    credibility_scorable: bool


class ExtractionResult(BaseModel):
    """
    Wrapper for LLM structured output.
    OpenAI response_format requires a top-level object, not a bare array.
    """
    items: list[GuidanceItem]


class GuidanceRecord(GuidanceItem):
    """
    Extends GuidanceItem with run metadata for PostgreSQL storage.
    Company and quarter are added here — not generated by the LLM.
    """
    company: str           # e.g. "Fineotex Chemical"
    quarter: str           # e.g. "Q4 FY26"
    prompt_version: str    # e.g. "v8"
    run_id: str            # UUID or timestamp string — ties all items from one run together
    extracted_at: datetime = datetime.now()
